### ISSUE TITLE
Bug: 2 bugs - artifacts and blender will exit after the "p" key pressed

### ISSUE THREAD

**Issue by Akira1San** [UPBGE/blender#11] opened 2016-01-07 14:42 UTC
Ive found 2 bugs with the latest compiled version from git.
1 - artifacts on the ground mesh.
2 - select VA and blender will exit after the "p" key pressed.
The game is http://sintelgame.org/ open -> desert_level.blend
Vid -> https://www.youtube.com/watch?v=HrRLnel6NKc

**Comment by panzergame** [comment] 2016-01-07 22:08
I cannot reproduce the both bugs but we already noticed some bug with textures the unfinished fix is on ge_material in this same repository, i hope it fix these bugs.

**Comment by Akira1San** [comment] 2016-01-08 08:47
Ok, im gonna ask on the forum to see if others will have the same crash with the va`s. But im more for the vbo`s.

**Comment by youle31** [comment] 2016-01-08 11:30
I can reproduce the crash. But not in debug mode. I'll see later if I can do something

**Comment by Akira1San** [comment] 2016-01-26 13:23
Tested with the latest commit(63,013) and no exits.

**Comment by panzergame** [comment] 2016-01-27 17:06
fixed in commit f38a0079a3bf6b265000edf68476194e92097db2 and 8a84fe8e341d02738ea77e3a05a662748cd1d74d.

**Closed** 2016-01-27 17:05 UTC
