### ISSUE TITLE
Render To Texture

### ISSUE THREAD

**Issue by EndSSgamesStudio** [UPBGE/blender#940] opened 2018-11-18 03:40 UTC
Hi!
I'm having a problem with "RenderToTexture"
simply does not work after these updates

gives an error that "Refresh" is not assigned ...
Did you switch to another?

![screenshot_20181118013436](https://user-images.githubusercontent.com/35436445/48668340-233c8280-ead2-11e8-9c51-2b05e8675860.png)
I do not find information about this in API... (Probably because this version was not released!)

What can I do to solve it?
http://pasteall.org/blend/index.php?id=50731

**Comment by youle31** [comment] 2018-11-19 08:01
Hi the issue is that you created a boolean game property named "RenderToTexture" whereas this property sould only be created in the script:

![sans titre](https://user-images.githubusercontent.com/10052509/48693395-9ed52700-ebd9-11e8-9922-ae68892a3c05.jpg)

You just need to remove the game property on the left

**Comment by EndSSgamesStudio** [comment] 2018-11-19 15:07
had perceived this problem...

_anyway it does not render the camera in the texture_

![screenshot_20181119130418](https://user-images.githubusercontent.com/35436445/48715334-ebc9f500-ebfb-11e8-8400-2e1b818cf5b1.png)

and he's not saying anything😕

![screenshot_20181119130516](https://user-images.githubusercontent.com/35436445/48715379-0a2ff080-ebfc-11e8-8a5f-ad8c2d4c0493.png)

**Comment by youle31** [comment] 2018-11-19 15:57
For me it works when we remove the game property "RenderToTexture" in last upbge master:

![sans titre](https://user-images.githubusercontent.com/10052509/48718141-17a8a300-ec1b-11e8-9c0e-5d590a773f32.jpg)

I don't know what's wrong. Maybe a problem with the build you are using?... I tested too with last windows build downloaded from upbge website and it is working for me

**Comment by EndSSgamesStudio** [comment] 2018-11-19 17:33
that's weird... @youle31 
I'll try to re-compile later...

**Comment by EndSSgamesStudio** [comment] 2018-11-20 04:02
I Re-Compiled, refresh the lib
and it did not work!

this is version 0.2.3:

![0 2 3](https://user-images.githubusercontent.com/35436445/48750780-05a12180-ec68-11e8-8902-9296bf3bd86c.png)
it works!


this is my build 0.2.4 _(this is the same thing as the official build)_
![screenshot_20181120015927](https://user-images.githubusercontent.com/35436445/48750790-12be1080-ec68-11e8-9e9d-cf29a0d32967.png)

now, for you to be running in version 0.2.4
maybe it's something on my pc @youle31  😐

**Comment by lordloki** [comment] 2018-11-20 05:15
@EndSSgamesStudio Could you check the official build downloaded from upbge.org?
It is to discard if it is due to your build (diferent compiling options) or your PC.

**Comment by EndSSgamesStudio** [comment] 2018-11-20 15:34
@lordloki yesterday I also downloaded all the official Compilations...
and all with the same problem.

**Comment by panzergame** [comment] 2018-12-18 19:43
Hello,

I saw that the example file was modified, can someone provide the last example file version ?

**Comment by youle31** [comment] 2019-01-07 08:56
panzergame fixed ImagRender modelview. Else, as no dev can reproduce the bug, I fear we can't do anything here, then I close this to clean the tracker to focus on what we can do... Sorry

**Closed by youle31** 2019-01-07 08:56 UTC
