### ISSUE TITLE
textureLod not working in GLSL shader with ImageRender (bug)

### ISSUE THREAD

**Issue by adriansnetlis** [UPBGE/blender#528] opened 2017-07-06 15:23 UTC
I am rendering a texture using ImageRender module. I store it at one of the texture slots, load it in a custom GLSL shader.
The texture code looks like this:
```py
own["texture"] = bge.texture.Texture(own, 0, 0)
own["texture"].source = bge.texture.ImageRender(scene, camera, 512, 512, 0, bge.render.HDR_FULL_FLOAT)
own["texture"].mipmap = True
```
Every frame I run `own["texture"].refresh(True)`

When I use this texture in custom GLSL shader, it works, however, this is an issue. If I use it using textureLod(textureName, textureCoordinates, lodBias), it doesn't work. It is still sampled as sharp image with no resolution reduction. I am not quite sure what's causing this issue, but it's really bothering me because it looks like it's impossible to use mipmapped real-time rendered images in GLSL shaders(while it's possible to do so in custom 2D filters).

Blender version: UPBGE 0.1.8

**Comment by panzergame** [comment] 2017-07-09 13:50
@adriansnetlis : Do you have a simpler test file ?

**Comment by adriansnetlis** [comment] 2017-07-09 18:44
[Bloom1.zip](https://github.com/UPBGE/blender/files/1133963/Bloom1.zip)

Sorry, this one's kinda mess, it's the file on which I'm trying to make different filters.

**Comment by HG1-Public** [comment] 2017-07-11 17:50
Its a bug but also in the BGE. 
There are no mipmaps are generated.
in Texture.cpp the method KX_PYMETHODDEF_DOC(Texture, refresh, "Refresh texture from source").
the call unsigned int * texture = m_source->m_image->getImage(m_actTex, ts);  returns always a nullptr
So never a mipmap will be generated or updated.

@adriansnetlis:
You also have made two faults.
1. The camera and the plane are two different owners. so you have to set own["INITIALIZE"] = True
also on the plane, to don't always run the initialization.
2. When you use pass objects int an function you need an variable (bge.texture.ImageRender(scene, plane)
) which can be used as reference.
If you pass own["texture"].source = bge.texture.ImageRender(scene, own.parent) you need to continuously call this function because the reference will be lost. 

Here is a BGL workaround for the mipmap problem.
```
import bge
import math
from bgl import *

def filter_plane(cont):
	own = cont.owner
	scene = own.scene
	
	FILTER_VERTEX = """
		varying vec2 texCoord;
		
		void main(void) {
			texCoord = gl_MultiTexCoord0.st;
			gl_Position = gl_ModelViewProjectionMatrix * gl_Vertex;
		}
	"""
	
	FILTER_FRAGMENT = """
		varying vec2 texCoord;
		uniform sampler2D renderedTexture;
		
		void main(void) {
			//vec2 texCoord = gl_TexCoord[0].st;
			gl_FragColor = texture2DLod(renderedTexture, texCoord, 4.0);
		}
	"""
	
	active_camera = scene.active_camera
	own.parent.worldTransform = active_camera.worldTransform
	own.worldPosition = [0, 0, 2]
			
	if not "INITIALIZE" in own:
		own["INITIALIZE"] = True # different owner. You need to stet it here also true.
		plane = own.parent # you need to store the object into a variable.
		own["texture"] = bge.texture.Texture(own)
		#own["texture"].mipmap = True # mipmap generation broken 
		own["texture"].source = bge.texture.ImageRender(scene, plane)

	glBindTexture(GL_TEXTURE_2D, own["texture"].bindId)
	glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_MIN_FILTER, GL_LINEAR_MIPMAP_LINEAR)# or GL_LINEAR_MIPMAP_NEAREST
	#glGenerateMipmap(GL_TEXTURE_2D) # does not exist in BGL wrapper
	glTexParameteri(GL_TEXTURE_2D, GL_GENERATE_MIPMAP, GL_TRUE)

	own["texture"].refresh(True)
	
	shader = own.meshes[0].materials[0].getShader()
	if shader:
		if not shader.isValid():
			shader.setSource(FILTER_VERTEX, FILTER_FRAGMENT, 1)
		shader.setSampler("renderedTexture", 0)

```

**Comment by adriansnetlis** [comment] 2017-07-12 12:59
Wow, thanks for all the valuable info and bgl workaroung, HG1. You really know a lot more about shaders than I do :D

**Comment by HG1-Public** [comment] 2017-08-02 16:20
You should not close this. Because this is a bug and it should be fixed.

**Comment by panzergame** [comment] 2017-08-11 09:55
@adriansnetlis, @HG1-Public : Could you test with recent master ? For me it's working.

**Comment by HG1-Public** [comment] 2017-08-11 10:13
This will take some time because I get an build error in DeckLink.cpp.
I have to build without it. My computer is very slow (only 4GB ram).
error C2660: 'ImageBase::getImage': Funktion akzeptiert keine 2 Argumente	C:\Projekte\UPBGE\blender\source\gameengine\VideoTexture\DeckLink.cpp	558	1	ge_videotex
error C2660: 'ImageBase::loadImage': Funktion akzeptiert keine 4 Argumente	C:\Projekte\UPBGE\blender\source\gameengine\VideoTexture\DeckLink.cpp	553	1	ge_videotex

My last build was from 07.08.2017
But maybe it is a Windows or a Microsoft mouse driver problem or a Nvidia driver problem.

**Comment by panzergame** [comment] 2017-08-11 11:08
@HG1-Public : The compilation is fixed in master.

**Comment by HG1-Public** [comment] 2017-08-11 11:40
I can confirm that the compilation is fixed now.
And the issue has been fixed. Tested with Bloom1.zip.

**Closed** 2017-08-11 12:00 UTC
Labels: bug
