### ISSUE TITLE
Property Sensor run crazy in 0.2.4

### ISSUE THREAD

**Issue by BlenderDoc** [UPBGE/blender#1045] opened 2019-05-31 01:23 UTC
Hello.
The Property Sensor brings wrong Results in many Cases.

Example:
P1 = 0
P2 = 0
Sensor: P1 equal P2 -> False
Sensor: P1 not equal P2 -> True

or:
P1 = Timer 0.0
P2 = 3.0
Sensor: P1 greater P2 -> immediately True (with invert -> never True)
Sensor: P1 less P2 -> never True

Also Interval Mode, maybe more.

[UpBGE Prop Sensor Bug.zip](https://github.com/UPBGE/blender/files/3239298/UpBGE.Prop.Sensor.Bug.zip)

Thank You for helping.
Regards, Doc

Edit ..........
Also 0.2.3. it seems.

**Comment by joelgomes1994** [comment] 2019-05-31 15:47
If I'm not wrong, it was never possible to use a property name in the **Property** sensor's _Value_ field, only literal values (like 3.0, as in the given example file), it's not a bug, it's simply a non-existing feature. If you need to campare two properties, try using the **Expression** controller.

![image](https://user-images.githubusercontent.com/19820741/58717553-de0edc80-83a1-11e9-8ae7-04a2b75ec3e4.png)

**Comment by youle31** [comment] 2019-05-31 18:56
Actually it seems a limitation in upbge as the code was changed.

I'd have a potential fix for this specific case: 

`
diff --git a/source/gameengine/GameLogic/SCA_PropertySensor.cpp b/source/gameengine/GameLogic/SCA_PropertySensor.cpp
index 6cee6d4e0a0..faf370b0d5d 100644
--- a/source/gameengine/GameLogic/SCA_PropertySensor.cpp
+++ b/source/gameengine/GameLogic/SCA_PropertySensor.cpp
@@ -218,6 +218,14 @@ bool SCA_PropertySensor::CheckPropertyCondition()
 				CM_StringTo(m_checkpropval, ref);
 				float val;
 
+				EXP_Value *compprop = GetParent()->FindIdentifier(m_checkpropval);
+
+				if (compprop->GetValueType() == VALUE_FLOAT_TYPE) {
+					if (!compprop->IsError()) {
+						ref = compprop->GetNumber();
+					}
+				}
+
 				if (orgprop->GetValueType() == VALUE_STRING_TYPE) {
 					CM_StringTo(orgprop->GetText(), val);
 				}
`

but if we want to fix everything, this would need some work. And I'm not totally sure neither about my patch then it would need panzergame or lordloki review. I think upbge development is paused/stopped then I guess it is better to use workarounds with expressions or other systems...

**Comment by BlenderDoc** [comment] 2019-05-31 23:35
Thank You. I afraid UpBGE has stopped. But as long this Site exists, i'll report a Bug if i find one. Maybe a Dev is bored some Day and want to do something nice. I'll keep Fingers crossed. :)

**Comment by youle31** [comment] 2019-08-12 16:25
As this is not a bug, but more a limitation (or maybe the old bge devs just replaced the old behaviour in property sensor with the expression controller), I close this task

**Closed by youle31** 2019-08-12 16:25 UTC
