### ISSUE TITLE
Toolbar icons shifted/missing

### ISSUE THREAD

**Issue by Gorgo13** [UPBGE/blender#1065] opened 2019-10-21 09:37 UTC
Hi there,

I noticed that in "UPBGE-EEVEE-Win64-2019-10-17", the icon shortcuts in the viewports are corrupted: the icon themselves are shifted compared to what they should correspond to: 
-the "Zoom" shortcut has no image, then below the "Move" displays the Zoom icon, the "Switch Camera" shortcut displays the Move icon. Only the Ortho/Persp icon is correct
-at the top, the same affects the viewport render modes (no icon for "x-ray", etc).

This is shown in the attached image.
![UPBGE_gizmos](https://user-images.githubusercontent.com/37718864/67194309-25e8db80-f3f7-11e9-9d9d-de526e26d9d5.png)

**Comment by lordloki** [comment] 2019-10-21 10:24
Thanks, i will check it

**Comment by lordloki** [comment] 2019-10-21 12:49
The issue is that i left everything ready for a new contraint joint icon but i didn't commit that icon. When i have time i will do.

**Comment by Gorgo13** [comment] 2019-10-21 18:44
Okay, thank you!

Just a quick question: do you kow if anyone in the development team is working on a fisheye projection for eevee? I know it would not be working properly for low poly scenes, but I guess that it should work for higher polycount. I would actually need that for an educational project (I'm working on a full simulation of a remotely operated 1-m professional telescope and need to realistically simulate wide angle (fisheye) webcams).

**Comment by lordloki** [comment] 2019-10-21 18:45
I dont know. I have no contact with the eevee developer team

**Comment by Gorgo13** [comment] 2019-10-21 18:47
Okay thanks...

**Comment by lordloki** [comment] 2019-10-21 21:23
Fixed in upbge0.3 branch. New build uploaded with the fix.

Thanks for reporting.

**Closed by lordloki** 2019-10-21 21:23 UTC
