### ISSUE TITLE
Parallax difference between Windows and Ubuntu

### ISSUE THREAD

**Issue by Masterblop** [UPBGE/blender#351] opened 2016-12-30 10:57 UTC
Hello everyone, I noticed the rendering differences between windows and ubuntu.
Hardware used:
AMD fx 8350
Gigabyte HD 7970

Windows use the latest drivers "Crimson Relive Edition 16.12.2 Optional";
Ubuntu use the open source drivers Oibaf:

glxinfo | grep 'version'
server glx version string: 1.4
client glx version string: 1.4
GLX version: 1.4
    Max core profile version: 4.5
    Max compat profile version: 3.0
    Max GLES1 profile version: 1.1
    Max GLES[23] profile version: 3.1
OpenGL core profile version string: 4.5 (Core Profile) Mesa 13.1.0-devel
OpenGL core profile shading language version string: 4.50
OpenGL version string: 3.0 Mesa 13.1.0-devel
OpenGL shading language version string: 1.30
OpenGL ES profile version string: OpenGL ES 3.1 Mesa 13.1.0-devel
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.10

I attach the differences images
![screenshot parallax ubuntu](https://cloud.githubusercontent.com/assets/11289405/21563890/ffa61444-ce86-11e6-8246-e2f996678c89.png)
![screenshot parallax windows](https://cloud.githubusercontent.com/assets/11289405/21563891/ffaac34a-ce86-11e6-955b-df20a9f62a26.png)

**Comment by panzergame** [comment] 2016-12-30 15:37
@Masterblop : An issue producing similar artefacts was fixed yesterday, could you try with the latest master please ?

**Comment by Masterblop** [comment] 2016-12-30 16:35
@panzergame on latest:
![schermata da 2016-12-30 17-33-30](https://cloud.githubusercontent.com/assets/11289405/21568617/510ef862-ceb6-11e6-9878-8ddcf8388a23.png)

**Comment by panzergame** [comment] 2016-12-30 17:02
@Masterblop : Could you send your example file ?

**Comment by Masterblop** [comment] 2016-12-30 17:41
Shure! 
http://www.filedropper.com/mzparallaxtestshare

**Comment by Masterblop** [comment] 2016-12-30 17:44
Shure! http://pasteall.org/blend/index.php?id=44866

**Comment by Masterblop** [comment] 2016-12-30 17:45
@panzergame

**Comment by lordloki** [comment] 2016-12-30 18:17
In the 2 cases, are you using the same number of steps?

Take into account that as you increases the deep using the bump scale parameter you will need more steps to avoid the banding problem.

**Comment by youle31** [comment] 2016-12-31 04:23
I made a test beetween my windows and my Linux mint 18 with GTX 970 (proprietary drivers) and I have the same result on the 2 OS: The image bands. Increasing number of steps makes the parallax more smooth... So I can't reproduce the bug :/ .

**Comment by Masterblop** [comment] 2016-12-31 10:02
At this point I fear that the fault is of the open drivers
![schermata da 2016-12-31](https://cloud.githubusercontent.com/assets/11289405/21576976/85d438ea-cf48-11e6-9001-e4058354df65.png)
![schermata da 2016-12-31 10-54-19](https://cloud.githubusercontent.com/assets/11289405/21576977/92670e98-cf48-11e6-8ace-f35661af8393.png)

**Comment by youle31** [comment] 2017-01-04 07:44
@Masterblop : With panzergame (him on Linux GTX 750 Ti (I don't know what driver he has)) and me on windows (gtx 970), we both have image with bands. So the result is different according to hardware and drivers hehe :P

**Comment by Masterblop** [comment] 2017-01-04 08:55
@youle31 @panzergame  Just out of curiosity, could you upload a screenshot to see the differences? 
Thanks in advance :)

**Comment by youle31** [comment] 2017-01-04 09:42
For me: http://pasteall.org/pic/show.php?id=110766

**Comment by Erstus** [comment] 2017-01-29 20:52
I got the same sort of banding on linux mint as Masterblop got on ubuntu. [http://pasteall.org/pic/index.php?id=111913](http://pasteall.org/pic/index.php?id=111913)

glxinfo | grep 'version'
server glx version string: 1.4
client glx version string: 1.4
GLX version: 1.4
OpenGL core profile version string: 3.3.0 NVIDIA 340.101
OpenGL core profile shading language version string: 3.30 NVIDIA via Cg compiler
OpenGL version string: 3.3.0 NVIDIA 340.101
OpenGL shading language version string: 3.30 NVIDIA via Cg compiler

**Comment by adriansnetlis** [comment] 2017-03-17 23:11
Confirmed the same result.

GPU: GeForce GTX 960M
Driver: nvidia-367.57
OS: Linux Ubuntu 16.10

glxinfo | grep 'version'
server glx version string: 1.4
client glx version string: 1.4
GLX version: 1.4
OpenGL core profile version string: 4.5.0 NVIDIA 367.57
OpenGL core profile shading language version string: 4.50 NVIDIA
OpenGL version string: 4.5.0 NVIDIA 367.57
OpenGL shading language version string: 4.50 NVIDIA
OpenGL ES profile version string: OpenGL ES 3.2 NVIDIA 367.57
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.20
    GL_EXT_shader_implicit_conversions, GL_EXT_shader_integer_mix, 

I suggest making test files for UV coordinate modifications and for mipmaps and test on both OS to look for the issue? Cuz there are 3 ideas for me atm: each OS handles mipmaps a bit differently, each OS handles UV coordinate modifications differently(this one sounds unbelivable, though) and the third one - some part of code doesn't work in one OS.

I hope that you can fix this, guys. By the way - the weird distance behaviour of the parallax was bothering me a bit, but I didn't know that this happened on my OS much more "drasticly".

**Comment by Akira1San** [comment] 2017-03-18 07:19
Perhaps after switching core OGL 3.3 it will be fixed. :)

**Closed** 2017-05-02 21:50 UTC
Labels: bug
