### ISSUE TITLE
object constraint bug

### ISSUE THREAD

**Issue by supermoaaa** [UPBGE/blender#277] opened 2016-10-31 20:45 UTC
hi, if you use a rigid Body joint in Hinge mode and you activate limits x angle 

wen you set a force on children object with applyMovment the limits is   ##broken

**Comment by sdfgeoff** [comment] 2016-11-02 22:26
applyMovement is not the correct way to apply a force as it has no regard for physics. Use worldLinearVelocity or localLinearVelocity or applyForce instead.

**Comment by lordloki** [comment] 2016-11-03 09:45
applyMovement teleports one object from one location to another. 
Closing as it is not a bug as @sdfgeoff pointed

**Comment by supermoaaa** [comment] 2016-11-03 20:42
hi I have exactly the same problem with apply force

**Comment by lordloki** [comment] 2016-11-03 21:35
Could you share a blend showing the bug?

**Comment by supermoaaa** [comment] 2016-11-04 08:16
Yes of course


https://www.mediafire.com/?yj5mo5447xxb8l5

ps: sorry i have a problem with github upload this is why a uploaded it on mediafire

**Comment by panzergame** [comment] 2017-01-26 20:27
My example test about hinge constraints is: http://pasteall.org/blend/index.php?id=45266
As you can see all is working as excepted. But in your file the right leg is doing things odd, as it is only one leg and that it is managed by a complex script: I asked you if you could provide an example more simpler avoiding to debug the python script. Thanks in advance.

**Comment by panzergame** [comment] 2017-01-26 20:35
My example file is http://pasteall.org/blend/index.php?id=45267, in this file there's two level of hinge constraints and i apply a force to the final child object. As you can see the limits are working fine. But in your file i have some odd behaviour with the right leg. As your example file is using a complex script and that only one leg is affected, i asked you if you could propose a simpler example avoiding to debugging/understand the python script. Thanks in advance.

**Comment by supermoaaa** [comment] 2017-02-06 20:23
at home the problem Appears with the left leg after long time
when we use hinge constraints in simple context it work very well but when we are in complex environment
the limits a broken. I'm trying to reproduce the bug in another context and i'll post it

**Closed** 2017-05-02 21:52 UTC
