### ISSUE TITLE
Performance Issue

### ISSUE THREAD

**Issue by Masterblop** [UPBGE/blender#1002] opened 2019-01-28 17:04 UTC
Hello guys,
I'm making a scene to share in the future.
I've tried both the UPBGE version 0.2.4 and the master branch. I always get low fps. With official Blender (2.79b and master), I reach 60 fps. I enclose screenshots and links to the file.

https://mega.nz/#!vUxkVCzR!OU9BG5lc2zlJ43WdIk_qHvMhK_QRqRmWZhdQOy-503s

UPBGE v0.2.4:
![schermata da 2019-01-28 17-22-09](https://user-images.githubusercontent.com/11289405/51852523-91998e80-2326-11e9-97f8-308a49c3ab50.png)

Official 2.79b:
![schermata da 2019-01-28 17-23-05](https://user-images.githubusercontent.com/11289405/51852550-9cecba00-2326-11e9-9c39-b8387262e63f.png)

**Comment by RomStef** [comment] 2019-01-29 09:04
Hi , 
In upBGE 0.2.4  the scene reach 15 fps
In Blender official 2.79b the scene crashes

i think it's my laptop but there is my opinion :
    The scene is too expansive, try to link objects because 234.000 at same place are too many.
    There are HD texture even on objects far from the camera.
    Enable camera culling to avoid the process of all geometries outside the frustum cone.

My hardware :
Intel I7-7500U 2.7Ghz
12 GB DDR
Intel HD Graphics 620 + GeForce GTX 950m in shared memory

The real time rendering need more optimization.

**Comment by Jesusemora** [comment] 2019-01-30 13:57
"Do you have unapplied modifiers?
Yes, some object have a bevel modifiers (light)"
don't use modifiers in bge.
is backface culling disabled in upbge?

**Comment by Akira1San** [comment] 2019-01-30 14:39
You have the render queries on?

**Comment by lordloki** [comment] 2019-01-30 16:05
From screenshots, it seems.
Debug render queries are very process consuming. Please, unset them and try again.

**Comment by UglinessInTheUI** [comment] 2019-02-16 21:21
Here is the fps on a RX580 8GB GPU with an FX 8350 CPU. Something is definitely wrong with your scene. I get very good fps in Unreal Engine and Cry Engine with scenes much more complicated than yours. UPBGE gives 5 fps and 2.79b gives 33 fps. Very bad bad scene. Some kind of corruption in the scene i guess. It's not supposed to be 400+ MB in size. Check to see what makes the file so big. Did you bake some high resolution textures ?

![upbge 5x lower fps](https://user-images.githubusercontent.com/12206146/52905303-a797c200-31f5-11e9-9a89-e285424531d3.png)
![house 2 79b](https://user-images.githubusercontent.com/12206146/52905304-a797c200-31f5-11e9-93c7-af783a5a282f.png)

**Comment by UglinessInTheUI** [comment] 2019-02-17 00:35
I disabled the shaders and the shadows and left only the lights and performance went back to 60 fps in 2.79b. Check the shaders and the shadows.

![2019 02 16-17 33](https://user-images.githubusercontent.com/12206146/52906786-0880c380-3211-11e9-9b97-87b0cd57b9e8.png)

**Comment by Masterblop** [comment] 2019-02-17 10:47
I need a few days of work on this scene. 
The intention is to replace windows (I used archimesh to create them), with windows with less polygons. For the shaders at the moment, I do not know how to improve them. In the past I tried to scale the textures to 1024 and reduce the export quality, but it was horrible to see (too many artifacts).

**Comment by lordloki** [comment] 2019-02-17 10:55
The main difference is that in upbge scene you are setting on the "Show render queries". This option is only to check the render queries and have a lot impact on fps. To compare bge and upbge, please, disable that option.

**Comment by Masterblop** [comment] 2019-02-17 11:16
> The main difference is that in upbge scene you are setting on the "Show render queries". This option is only to check the render queries and have a lot impact on fps. To compare bge and upbge, please, disable that option.

@lordloki Is this message for me?

**Comment by UglinessInTheUI** [comment] 2019-02-18 07:53
With render queries turned off i get 9 fps in UPBGE and 33 fps in 2.79b. If i turn off all render options and leave only the lights on i get 60 fps in 2.79b. It's still 3 times slower in UPBGE compared to 2.79b.

**Comment by UglinessInTheUI** [comment] 2019-02-18 08:17
The issue is not the polygons. There is something else wrong in that scene. I think scenes that were saved with both UPBGE and 2.79b get corrupted and become useless. You have to append each element from the old scene into a new scene and check the impact on performance after each append. There are 2 million displaced triangles in this scene and i get 128 fps. That's why i don't think it's the polygons. Your scene has only 500,000 triangles. It's the shading and the baked textures or something else.

![2019 02 18-01 15](https://user-images.githubusercontent.com/12206146/52936868-ccd22080-331a-11e9-876d-a097e4fca8a4.png)

**Comment by UglinessInTheUI** [comment] 2019-02-18 09:32
Here is a quick fix for that house scene. If i delete all the lamps/lights from layer 15 my fps goes back to 100+. Disabling layer 15 doesn't seem to fix it or to be enough. You have to actually delete all the lamps from layer 15. 

![2019 02 18-02 25](https://user-images.githubusercontent.com/12206146/52941059-322b0f00-3325-11e9-908e-0be54bf63a6f.png)

**Comment by Masterblop** [comment] 2019-02-18 09:36
Doing so only the flat textures remain (only Diffuse)

**Comment by UglinessInTheUI** [comment] 2019-02-18 09:40
The problem is that UPBGE is still 7 times slower compared to 2.79b even if i delete everything in layer 15. So it's not really a good fix as far as UPBGE is concerned.

![2019 02 18-02 36](https://user-images.githubusercontent.com/12206146/52941611-766adf00-3326-11e9-8241-ae613dcb9e9a.png)

**Comment by UglinessInTheUI** [comment] 2019-02-18 09:49
There is definitely a bug in the layers system because if i disable layer 15 doesn't seem to fix it or to be enough. I have to actually delete all the lamps from layer 15 in order to disable it completely. Theoretically it should be enough to just disable layer 15. Anyway , it doesn't seem to fix it for UPBGE.

**Comment by youle31** [comment] 2019-08-12 16:32
Performances issues can't be tracked comparing old bge and upbge, as many things have changed, and as the scenes need to be adapted and optimized to run correctly in upbge. If bge runs better for you, you can still use it, else you can try different upbge version if you like one more than another. I just added last upbge builds based on last 2.7 master here: https://github.com/UPBGE/blender/issues/1041 if you want to give a try. I close this as we can't do anything with the informations provided

**Closed by youle31** 2019-08-12 16:32 UTC
