### ISSUE TITLE
UPBGE crashes mid-runtime

### ISSUE THREAD

**Issue by Nemescraft** [UPBGE/blender#592] opened 2017-09-08 20:07 UTC
I run my game.  I fire my gun (which basically just shoots a cube with an addObject actuator). After some firing, UPBGE crashes. This is probably not because of the **gun**, but because of some script running in the background.

Here is the issue on BA (with .blend):
[https://blenderartists.org/forum/showthread.php?437488-UPBGE-crashes-after-firing-the-gun-sometimes&p=3235759#post3235759](url)

**Comment by Nemescraft** [comment] 2017-09-09 13:25
OK, solved it. The "bug" was that the addObject actuator was trying to delete something that did not exist anymore.

**Comment by panzergame** [comment] 2017-09-10 13:35
Reopened as user should never handle segfault but error message only.

**Comment by Nemescraft** [comment] 2017-09-10 15:07
Well, I mean it is probably still a bug, but I just diabled the time setting on the addObject actuator.

**Comment by TryExceptElse** [comment] 2017-09-15 04:54
This appears to be a duplicate of #574 . I was able to reproduce it in the initial version of 0.1.9 but not later builds.

**Comment by panzergame** [comment] 2017-09-17 17:53
@Nemescraft: Could you confirm that it still appears without your workaround ? (Is the file in BA updated ?)

**Comment by Nemescraft** [comment] 2017-09-18 18:39
Well, I could try to see if it crashes on purpose, but why do it when I know what the problem is? `addObject` actuator was trying to delete an object after sufficient time had passed, but because that object didn't exist anymore, due to an `endObject` actuator that is activated upon collision on the bullet, it caused the file to crash. It would be nice if it just displayed: `Error: Object "Spawner", actuator "Fire", delete object timer: Object to delete not found` or something like that. But OK, I will try to cause the bug on purpose. EDIT: Yes, the bug is still caused, naturally, but I'm using UPBGE 0.19. I don't know if it is in 0.20

**Comment by TryExceptElse** [comment] 2017-09-19 02:05
This bug was fixed by [47aa533](https://github.com/UPBGE/blender/commit/6c8598b3405d949ab97cae6e05a9460c59bd071c), although it seems the download on the upbge site has not been updated yet.

**Closed** 2017-10-01 20:20 UTC
