### ISSUE TITLE
Performance decrease in Animated trees file

### ISSUE THREAD

**Issue by youle31** [UPBGE/blender#262] opened 2016-10-17 03:46 UTC
http://pasteall.org/blend/index.php?id=43733

**Comment by panzergame** [comment] 2016-10-17 05:26
These 115 are constant after the game start ? Normally the conversion is a little bit more complicated, but the render the same.

**Comment by youle31** [comment] 2016-10-17 09:58
As the camera rotates, the fps is not constant... But there is a global performances decrease in this file after these 2 commits. I'll do more tests with several files to see if I can be more precise.

**Comment by Akira1San** [comment] 2016-10-17 13:22
Made a test too, img-> http://pasteall.org/pic/index.php?id=107723
The test is made with VBO + use frame rate off. 1: BF BGE, 2: compiled latest master, 3: ge_array.
But no settings have been touched such as material constants.

**Comment by Akira1San** [comment] 2016-10-19 01:14
Tested the Animation_TreesTest.blend and looks like: 
upbge 0.0.3 gives 140 fps, 0.0.4 90 fps, bf bge 2.8 130 fps. So the regression started from 0.0.4
sintel desert level 120 fps in 0.0.3, could it be, that the regression started with the change to the wires commit? So yeah Upbge 0.0.3 is the fastest of all. :)

**Comment by panzergame** [comment] 2016-10-19 12:15
@Akira1San, @youle31 : What happen if you use constants materials ? By running the script http://download.upbge.fr/download/script/constant_material.py you will setup all material constant. At least you can test by setting textures to constant.

**Comment by youle31** [comment] 2016-10-19 13:15
Almost no change. A little perf increase. I guess this is because most textures are other .blends...

**Comment by panzergame** [comment] 2016-10-19 13:19
@youle31 : If you set the other file to constant, what happen ?

**Comment by Akira1San** [comment] 2016-10-19 13:54
Compiled the latest master: File Animation_TreesTest.blend: still frame.
vbo 100 fps with no constants, with constants the fps started to flick like 100-99 fps. With VA 120fps. 
Bf BGE 2.78: VBO - 130fps, VA - 160 fps.
So like i said the regression started with 0.0.4  and this is really bad performance.

**Comment by panzergame** [comment] 2016-10-19 14:03
@Akira1San : Can you try the commit or the commit range introducing this performance issue ? Sorry i can't reproduce any of the the issues here :S.

**Comment by Akira1San** [comment] 2016-10-19 14:06
" commit or the commit range" whats that? will try it.

**Comment by panzergame** [comment] 2016-10-19 14:08
@Akira1San : Try reset step of 10 commits between UPBGE 0.0.3 and 0.0.4 (git tag v0.0.3, v0.0.4).

**Comment by Akira1San** [comment] 2016-10-19 14:12
Can i have some step by step instructions.

**Comment by youle31** [comment] 2016-10-19 14:19
I'll do it. With this file: http://pasteall.org/blend/index.php?id=43733?

**Comment by youle31** [comment] 2016-10-19 14:27
@panzergame : Do you think the bug can come from this commit in Akira_san trees file?: https://github.com/UPBGE/blender/commit/c6faae4b4782a9ae8c00e294eccc86be4efc6201

**Comment by panzergame** [comment] 2016-10-19 14:49
@youle31 : I think not…

**Comment by Akira1San** [comment] 2016-10-20 02:03
I was not able to sleep and so i did a lot of compile from 004 till 003. So i get to Hardware instancing commit and in there is also the same regression. so this is close to finding the big bug. Will continue tomorrow. Just reporting.

**Comment by panzergame** [comment] 2016-10-20 11:52
The issue about vertex color is fixed in 3ffa6229993e252433d755d187ad9037735022d9 ! :)
Indeed all the vertex were unique per face previously, now they back shared.

@youle31, @Akira1San : Can you confirm the performance back ?

**Comment by youle31** [comment] 2016-10-20 14:49
Congrats panzergame! It's ok for me :) I leave the issue opened to talk about the other trees issue.

**Comment by youle31** [comment] 2016-10-20 15:04
@panzergame: I don't know if this is the same commit, but for me performances in animated trees file are restored as in 0.0.3.

I wait for @Akira1San  to confirm.

**Comment by Akira1San** [comment] 2016-10-20 15:50
My test show: Now the fps is more stable and gives some +frames, but 0.03 gives 140fps -0.1.1 -100fps
Latest Master: 100 fps, bf bge 2.78: 130 fps, 0.0.3: 140 fps
Images:
http://pasteall.org/pic/index.php?id=107888  - master
http://pasteall.org/pic/index.php?id=107889  - bf bge 278
http://pasteall.org/pic/index.php?id=107890  - 0.0.3
Gonna continue with finding the commit.

**Comment by Akira1San** [comment] 2016-10-26 17:16
Made a test with compiled master: commit: UPBGE: Don't sort object for transparency object in shadow render.
Result: 0.1.1+ first 01.2 commit, 145fps in standalone. bf bge 2.78a: 125 fps, using vbo.
So now UpBge beats bf bge. :D

**Closed** 2016-11-03 22:12 UTC
Labels: ?, bug
