### ISSUE TITLE
Releasing key doesn't activate keyboard sensor

### ISSUE THREAD

**Issue by vlad1777d** [UPBGE/blender#196] opened 2016-08-26 22:30 UTC
Releasing key doesn't activate keyboard sensor.

Version: UPBGE_ge_vibration_v0.0.9b2.77d08192016hb40b91aLinux64.tar.xz	2016-08-19 20:21 	14M

Pressing works well:
`if activated in keyb.inputs[W].queue:`

But releasing doesn't works at all:
`deactivated in keyb.inputs[W].queue:`

I tried different ways, including:
`deactivated in keyb.inputs[W].status:`, 
and:
`deactivated in keyb.inputs[W].values:`
Nothing had worked.

![2016-08-27 01-21-39](https://cloud.githubusercontent.com/assets/12682937/18022165/50fda3c4-6bf5-11e6-83b7-c328f44a4d06.png)
![2016-08-27 01-22-05](https://cloud.githubusercontent.com/assets/12682937/18022166/50fe7a4c-6bf5-11e6-87cf-b4afed39ee7c.png)
![2016-08-27 01-24-57](https://cloud.githubusercontent.com/assets/12682937/18022167/50fec5b0-6bf5-11e6-89ad-bf4c959f452a.png)

P.S. In BGE all worked well: https://www.youtube.com/watch?v=HUHnxlEvPZ8
Scripts for BGE: https://github.com/vlad1777d/subterrain (may be a little outdated)

**Comment by panzergame** [comment] 2016-08-27 12:50
I cannot reproduce your bug in current master. I tested with the file: http://pasteall.org/blend/index.php?id=43239

**Comment by vlad1777d** [comment] 2016-08-27 12:57
That's all because you have all sensor, not keyboard.
Here is .blend with a bug: http://dropmefiles.com/58Bwr

**Comment by youle31** [comment] 2016-08-28 15:14
Hi, I don't know if this is a bug or not (I let panzergame judge this) but this is a bit weird when you have a keyboard sensor to check python keyboard status instead of sensor status: http://pasteall.org/blend/index.php?id=43252

**Comment by vlad1777d** [comment] 2016-08-28 15:47
Hello youle31, thank you for expressing of your opinion.

It's really interesting, that your way works well, thank you.

Why I have done with such "weird" way?
Because in the plans I'll have the module named: input.py, which could import all other modules, including player.py, with porting which from BGE to UPBGE I have problems.
And, as we know, the nested module cannot receive access to his parent's module's attributes, in which will be keyboard sensor.

I had not done this with player.py because I had not finished it yet, but I had already done this with gun animations (gun_animations.py) and gun proceeding (gun_gravity.py) modules, look please here:
https://github.com/vlad1777d/subterrain/blob/master/keys_input.py

So I'm not a mad coder, which wrights his code as strange, as he can.
This approach was caused of the security politics of Python language, I agree with it.

Of course, I could receive object, on which there are Python controllers, than receive the controller from it, than check it's status, but this would be a long and a weird way in our case.

Also such approach worked well in BGE 2.77: http://dropmefiles.com/1Ww72

Anyway, I'll wait for a decision about this from people, who are writing this engine.

**Comment by panzergame** [comment] 2016-08-28 15:52
@vlad1777d : I see the bug your talking about.

I have a solution but it will be always a little issue. The solution is to call the keyboard sensors internally if the input queue is not empty. But what will happen if the key is pressed and released in the same frame. The sensor will be positive or negative ? For me the best is to be optimistic and made positive priority negative. 

@vlad1777d : Do you agree with this behaviour ?

**Comment by vlad1777d** [comment] 2016-08-28 16:07
panzergame, thank you for answering.

It's good decision, but it will not work and cause problems in modules where:
pressing key will cause starting animation; releasing key will stop animation.

If you'll press and release key in one frame (if you can press keys with speed 60 times per second =) ), than animation will start playing, and will not stop until player will press and release key next time 
(of course, if he will not press and release it at the same frame)

So, I think, as **releasing always goes after pressing**, **releasing cannot be without pressin**g, so releasing must have a priority to pressing.

I wanted to write you that:
_---If I understoor right from the API WIKI, the queue has not only values of keyboard from current frame, but from the previous frame too----_ 
but I mistaken and this was from the status parameter.
But there was a controversial expression, than it'll be good if you corrected this (or asked people, who is responsible for that). 
Expression:
_The list always contains one value. The first value of the list is the last value of the list in the last frame. (read-only)_

Thank you. 
And sorry for I'm writing so long, I don't know English well and use a translator for unknown words.

**Comment by panzergame** [comment] 2016-08-28 17:09
```So, I think, as releasing always goes after pressing, releasing cannot be without pressing, so releasing must have a priority to pressing.```

There's no case where the negative event undo the positive event and then doesn't works for our case ?

**Comment by vlad1777d** [comment] 2016-08-28 17:18
@panzergame , maybe in case when releasing starts animation and pressing stops animation =)

Or in cases if pressing adds value to Python's attribute (for example, +5), releasing - removes (-5).
Then value will reduce on 5 instead of staying constant.

But such cases, as I think, can happen very rarely. And cases when human will pres and release key at one frame, as I think, maybe never. So take in mind such cases, as I think, it's not necessarily.

Also, if programmer makes his game with taking into account such rare behavior

**Comment by panzergame** [comment] 2016-09-08 16:55
Sorry for the delay, but with development cycle bugs will be focused the next week.

**Comment by vlad1777d** [comment] 2016-09-08 23:07
Thank you, this is not a problem.
We all have ours business and cares =)

**Comment by panzergame** [comment] 2016-09-11 16:00
@vlad1777d : Could you test the branch ge_keyboard_sensor ?

**Comment by vlad1777d** [comment] 2016-09-11 16:54
@panzergame Yes, of course. I'll do this in the evening today or tomorrow and will write you report.

**Comment by panzergame** [comment] 2016-09-11 17:05
Thanks you, in this branch the behaviour is:
- Active the sensor when the wanted key(s) contains a non-empty event queue.
- Set the sensor positive only if the last handled status of the key is positive too, else false.

**Comment by vlad1777d** [comment] 2016-09-11 17:07
@panzergame ,  I'll continue porting there my demo level, I think that in work process I can find all bugs, if they are present.

**Comment by vlad1777d** [comment] 2016-09-13 16:50
@panzergame , sorry for such a late answer, but I cannot build it.
There is an error when I try to launch "GNUmakefile":
http://pastebin.com/LQH6HSrT

There is not any .configure script and no instructions: how to build.
(system: Debian unstable x64 Cinnamon)

**Comment by panzergame** [comment] 2016-09-13 16:54
UPBGE is compile the same way as blender https://wiki.blender.org/index.php/Dev:Doc/Building_Blender

**Comment by vlad1777d** [comment] 2016-09-13 16:59
I'll try.

**Comment by vlad1777d** [comment] 2016-09-13 18:14
It's written:

```
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Package libtiff-dev is a virtual package provided by:
  libtiff5-dev 4.0.6-2
  libtiff4-dev 3.9.2-2kxstudio0.14
You should explicitly select one to install.

E: Package 'libtiff-dev' has no installation candidate
E: Unable to locate package libopenjpeg-dev
ERROR! apt-get failed to install requested packages, exiting.
```

I installed libtiff5-dev 4.0.6-2 manually, but I got an error again.

**Comment by youle31** [comment] 2016-09-13 21:21
http://download.upbge.fr/download/buildbot/branch/

**Comment by vlad1777d** [comment] 2016-09-13 23:41
Thank you.

**Comment by panzergame** [comment] 2016-09-17 17:09
@vlad1777d : Did the branch is working for you ?

**Comment by vlad1777d** [comment] 2016-09-18 18:33
@panzergame Sorry, I had no time to use it. I'll check one script now and answer you here.

**Comment by youle31** [comment] 2016-09-23 14:23
Hi! We normally make the release in the week end. @vlad1777d : Could you tell us if all is right with panzergame fix? Did you encounter other bugs? Thanks

**Comment by vlad1777d** [comment] 2016-09-24 15:10
@youle31 Now it works well.

**Comment by youle31** [comment] 2016-09-24 16:20
Thanks for report && thanks @panzergame  for the fix

**Closed by youle31** 2016-09-24 16:20 UTC
Labels: bug
