### ISSUE TITLE
SOLVED: Unable to compile UPBGE in Ubuntu 14.04.

### ISSUE THREAD

**Issue by chicortiz** [UPBGE/blender#548] opened 2017-07-31 19:46 UTC
Hello UPBGE team!

I have followed the instructions bellow and and I got some compilation errors. I'm using Ubuntu 14.04.

###
Compile from source :

First, download our git repository.
git clone https://github.com/UPBGE/blender && cd blender

Then, install dependencies :
./build_files/build_environment/install_deps.sh

Compile :
make

Then, run :
cd ../build_linux
./blender
###

Here is the full log if you want to check it out:

https://pastebin.com/M0uQHdCe

If you need additional details don't hesitate in asking. :)

Greetings,

Ortiz

**Comment by panzergame** [comment] 2017-07-31 20:27
Hello,

I could not reproduce the compile error with BBPlayer enabled, could you provide your `build_linux/CMakeCache.txt` file please ?

Else you can disable the option `WITH_GAMEENGINE_PPLAYER` by running `ccmake .` or an other cmake gui in `build_linux` directory.

**Comment by lordloki** [comment] 2017-07-31 21:51
Could you update to last master commit and compile again? 
I have committed a possible fix

**Comment by chicortiz** [comment] 2017-07-31 22:00
Hello @panzergame, Thank you again. I'm afraid I don't know where the build_linux/ directoy is located. Inside the Blender folder main I have "build_files".

@lordloki Thank you!

I'm sorry I don't know how to overwrite the Blender UPBGE folder.  Could you help me?
git clone https://github.com/UPBGE/blender && cd blender
Gave me this: fatal: destination path 'blender' already exists and is not an empty directory.

Yours,

Ortiz

**Comment by chicortiz** [comment] 2017-07-31 22:11
Hello @panzergame <https://github.com/panzergame>, Thank you again. Here is
my CMakeCache.txt: https://pastebin.com/02nJd7Rp

In which text the WITH_GAMEENGINE_PPLAYER is located? I need to comment or
erase this option?
I'm really sorry to be such a noob regarding compiling Blender. (‘-’*)

@lordloki <https://github.com/lordloki> Thank you!

I'm sorry I don't know how to overwrite the Blender UPBGE folder. Could you
help me?
git clone https://github.com/UPBGE/blender && cd blender
Gave me this: fatal: destination path 'blender' already exists and is not
an empty directory.

Yours,

Ortiz

2017-07-31 18:51 GMT-03:00 lordloki <notifications@github.com>:

**Comment by lordloki** [comment] 2017-08-01 04:13
The error comes from your compiler doesn't support C++11 features by default.
Possible solution:
- You have to set on enabling WITH_C++11 on CMake (using cmake gui i.e.)

**Comment by chicortiz** [comment] 2017-08-01 12:32
Hi @lordloki ! I now installed CMake from source. 
Do you think that Code::Blocks will do it as the graphic user interface?
I don't know where to start. How should I open the project inside Code Blocks? And what is "WITH C++11"? Is ita a... "Flag"?

**Comment by pqftgs** [comment] 2017-08-01 18:19
I'm on gcc 5.3 and this makes it work:
1. Run `ccmake .` in the build folder (the one with CMakeCache.txt)
2. Hit "t" for advanced mode
3. Find WITH_CXX11 and toggle ON
4. Configure/generate
5. `make -j4 && make install`

Afaik this is required unless you have gcc 6.0 or newer.

**Comment by chicortiz** [comment] 2017-08-01 19:46
Thank you @pqftgs ! I think I'm progressing.

Now I'm stuck here:
___
[ 88%] Linking CXX static library ../../../lib/libbf_freestyle.a
[ 88%] Built target bf_freestyle
make: *** [all] Error 2
___

Do you know any workaround? :)

**Comment by panzergame** [comment] 2017-08-02 09:39
Irrc i get this issue on the builbot because of an older gcc version, @chicortiz : Could you try an higher version, 6.3 or so ?

**Comment by panzergame** [comment] 2017-08-02 09:41
gcc 5x should be enought.

**Comment by chicortiz** [comment] 2017-08-02 12:27
@panzergame : Sure thing panzergame! I was suspicious of this gcc version. I will update and try again soon.

**Comment by chicortiz** [comment] 2017-08-02 15:59
Updated to gcc (Ubuntu 5.4.1-2ubuntu1~14.04) 5.4.1 20160904
Whoa! Close?

___
[ 98%] Building CXX object source/gameengine/Rasterizer/RAS_OpenGLRasterizer/CMakeFiles/ge_oglrasterizer.dir/RAS_StorageVBO.cpp.o
/home/chico/blender/source/gameengine/Rasterizer/RAS_OpenGLRasterizer/RAS_StorageVBO.cpp: In member function ‘void VBO::DrawBatching(const std::vector<void*>&, const std::vector<int>&)’:
/home/chico/blender/source/gameengine/Rasterizer/RAS_OpenGLRasterizer/RAS_StorageVBO.cpp:271:100: error: invalid conversion from ‘void**’ to ‘const GLvoid** {aka const void**}’ [-fpermissive]
 _mode, counts.data(), GL_UNSIGNED_INT, (void **)indices.data(), counts.size());
                                                                              ^
make[2]: *** [source/gameengine/Rasterizer/RAS_OpenGLRasterizer/CMakeFiles/ge_oglrasterizer.dir/RAS_StorageVBO.cpp.o] Error 1
make[1]: *** [source/gameengine/Rasterizer/RAS_OpenGLRasterizer/CMakeFiles/ge_oglrasterizer.dir/all] Error 2
make: *** [all] Error 2
____

Full log:
https://pastebin.com/1rJfEB9i

Greetings!

Ortiz

**Comment by panzergame** [comment] 2017-08-03 09:49
it should be fine in master now.

**Comment by chicortiz** [comment] 2017-08-03 14:57
Yay! :) Thank you so much for your patience guys!!!

goo.gl/793aiy
___

Here is how I'm proceeding at the moment (critics are VERY welcome):

1) Deleted the old folders (blender and build_linux).
2) git clone https://github.com/UPBGE/blender && cd blender
3) ./build_files/build_environment/install_deps.sh
4) make
5) Run ccmake . in the build folder (the one with CMakeCache.txt)
6) Hit "t" for advanced mode
7) Find WITH_CXX11 and toggle ON
8) Configure/generate
make -j4 && make install

___

Forgive me mine "bulldozer" kind of logic. In the end I'm a redneck. 
It's even an insult to name that as logic.
xD

**Closed** 2017-08-05 10:35 UTC
