### ISSUE TITLE
Environment Lighting not Working in Standalone

### ISSUE THREAD

**Issue by adriansnetlis** [UPBGE/blender#182] opened 2016-08-18 21:11 UTC
The environment lighting works well in viewport and emebed player, however, it doesn't work in standalone. When I run standalone, all my shadows are completely black. Thus I have to use hemis. It's not of a real problem, but yet - would be cool to get fixed.

**Comment by DCubix** [comment] 2016-08-19 00:41
Please provide us a demo file. For us to try to reproduce the bug :grin:

**Comment by youle31** [comment] 2016-08-19 09:52
@adriansnetlis : It's because of constant "world" values for materials:

example file: http://www.pasteall.org/blend/43214 (just uncheck world in plane's material options) and see.

(When you start embedded the envlight on the plane has already been computed in the viewport so the shadows are pink. In standalone, we restart from the beginning (what is already computed in the viewport is not taken into account))

So this is not a bug... But we may reconsider again the default constant for new materials.

I close the issue.

**Closed by youle31** 2016-08-19 09:52 UTC
Labels: ?, bug

**Comment by adriansnetlis** [comment] 2016-08-19 10:01
You could try changing the first constant step recalculation, but this seems very low priority.
