### ISSUE TITLE
Shaky camera with use frame rate off

### ISSUE THREAD

**Issue by Akira1San** [UPBGE/blender#587] opened 2017-09-03 18:00 UTC
Ive compiled the latest master and using this template -> https://blenderartists.org/forum/showthread.php?291532-Third-Person-Shooter-Movement-Example-File/page3 The bottom one.
When switch the "use frame rate off" the camera starts to shake, but with "use frame rate on" it dont. so i dont know if its a bug or its something with the python script.

**Comment by panzergame** [comment] 2017-09-03 18:53
Did it happens in 0.1.9 ?

**Comment by Akira1San** [comment] 2017-09-03 19:30
Ops, forgot to add it to the description. No it works fine in 0.1.9
The same file makes the camera go to the bottom in mathfu branch.

**Comment by youle31** [comment] 2017-09-10 10:35
I can't reproduce the shake

**Comment by panzergame** [comment] 2017-09-10 12:35
I have the player transformed in a missile when i uncheck use framerate, but this comes from bullet ""issues"" and is fixed by moving the player a little bit up.

**Comment by Akira1San** [comment] 2017-09-10 15:01
It looks like i had a merge problem, but now its fixed after re building.

**Closed** 2017-09-10 15:01 UTC
