### ISSUE TITLE
material ramp error?

### ISSUE THREAD

**Issue by REALHanzo** [UPBGE/blender#578] opened 2017-08-25 16:50 UTC
I had noticed this problem before I'm not sure why this happens but when I try to use the ramps the material totally disappears :P I think it may have to do with the number of lamps or shadows but I don't think that this should be an issue because sometimes it works fine and sometimes not so it may be worth looking into.

**Comment by panzergame** [comment] 2017-09-04 05:02
Do you have a file reproducing the bug ? Did it happens in BFBGE too ?

**Comment by panzergame** [comment] 2017-09-09 16:46
I can't reproduce such issue, I'm closing it waiting for proper information.

**Closed by panzergame** 2017-09-09 16:46 UTC
