### ISSUE TITLE
Parallax not working 

### ISSUE THREAD

**Issue by Masterblop** [UPBGE/blender#571] opened 2017-08-21 15:22 UTC
Tested versions 0.1.8 and 0.1.7 and works correctly.
In 0.1.9 does not work.

**Comment by panzergame** [comment] 2017-08-24 17:45
You are certainly using a modifier in the object using parallax, it's a current bug that will be fixed for next release.

**Comment by panzergame** [comment] 2017-08-24 17:47
Else, please provides more info, because if I trust you I will assume that you provide no info as the bug is reproducible in any case, but it's not, so the report is invalid.

**Comment by Masterblop** [comment] 2017-08-24 18:57
![upbge0 1 8parallax](https://user-images.githubusercontent.com/11289405/29683477-ce3da884-890e-11e7-8f4c-0ba3456099fd.jpg)
[Terra2.zip](https://github.com/UPBGE/blender/files/1249940/Terra2.zip)
![upbge0 1 9parallax](https://user-images.githubusercontent.com/11289405/29683479-ce62a440-890e-11e7-918d-9b6297016c4b.jpeg)

**Comment by panzergame** [comment] 2017-09-09 15:44
@Masterblop : The issue you have is caused by a the fact that your first texture (color map) have the option `Parallax` checked whereas i don't provide any height data, the only that do it is the last texture. So all the other textures should check `Use Parallax UV` instead.

Though that the behaviour in 0.1.8 is a bug because only one height texture is allowed and in 0.1.8 somehow the last texture was it. In 0.1.9 the first texture enabling the parallax option provide the height texture, in your case the height was empty so no parallax.

**Closed by panzergame** 2017-09-09 15:44 UTC
