### ISSUE TITLE
Bad Normals / reflection map on using draw call batching

### ISSUE THREAD

**Issue by BluePrintRandom** [UPBGE/blender#365] opened 2017-01-19 20:56 UTC
https://www.youtube.com/watch?v=_yRlDs69TTQ&feature=youtu.be

here is the bug in action

**Comment by BluePrintRandom** [comment] 2017-01-19 21:03
https://drive.google.com/file/d/0B29hKf6-B52cNDluNEl4TXYzUjA/view?usp=sharing

**Comment by panzergame** [comment] 2017-01-19 21:55
@BluePrintRandom : Are your uv layers from the mesh merged in the same order ? If not you should expect layer inversion.

**Comment by BluePrintRandom** [comment] 2017-01-19 21:57
there is only 1 UV map**

**Comment by BluePrintRandom** [comment] 2017-01-19 21:59
each object is using 1 giant sheet of materials and they are all uv mapped to the sheet

if you disable the script (batching) the normals etc look how they should,

**Comment by BluePrintRandom** [comment] 2017-01-20 02:07
Maybe I am doing something wrong with batching?

Did you check my code?

**Comment by panzergame** [comment] 2017-01-20 18:39
@BluePrintRandom : Your code is fine, can you try making the smallest case reproducing this bug ? It will help a lot. Also I confirm it with your file, it isn't platform dependents ect…. Thanks in advance.

**Comment by BluePrintRandom** [comment] 2017-01-22 23:12
If we strip out all game objects not using the material,  it should not change amything, 

(the script only batches objects using the material  MAAtlas I think)  and only objects using 1 material

Everything else in the scene just moves point lamps around,

**Comment by panzergame** [comment] 2017-01-25 21:49
@BluePrintRandom : Could you confirm that 5b9e154e3076c2c94b59381e2583747880b524c8 is fixing the issue ?

**Comment by BluePrintRandom** [comment] 2017-01-25 21:53
I will need a 2 win build (I don't have one setup atm)

I will be able to check tonight before bed most likely.

**Comment by youle31** [comment] 2017-01-25 22:18
@BluePrintRandom : Hello, could you check id the problem is solved in this build: https://drive.google.com/file/d/0B3GouQIyoCmrNzJCOWI4MDlHWmc/view?usp=sharing

panzergame did a fix.

Thanks!

**Comment by BluePrintRandom** [comment] 2017-01-26 06:03
I confirm it works like a charm!

Thank you so much!

**Closed** 2017-01-26 10:28 UTC
Labels: bug
