### ISSUE TITLE
IK Regression

### ISSUE THREAD

**Issue by BluePrintRandom** [UPBGE/blender#393] opened 2017-02-16 20:50 UTC
https://www.youtube.com/watch?v=tg2IcGILO0Q&feature=youtu.be

here is the regression

hit me back for a private test copy the project is now commercial .

**Comment by youle31** [comment] 2017-02-17 03:58
Hello, we'd need a simple/simplified test file to reproduce the bug. Without test file, we can do nothing

**Comment by BluePrintRandom** [comment] 2017-02-17 06:08
Youle has test file, please don't share the art as it's not mine - (it is copyright and owned by my artist) 
the code is GPL however**


Go to layer 1, and swap to active camera.

press P in 2.77 = runs fine

Press P in upbge 0.1.0 and others = neck Ik goes crazy 

to play the game WASD or arrows 
Q = swap actor
E = pick up item / drop
R = reload 

MOuse 1 = shoot
mouse 2 = zoom in / aim

**Comment by panzergame** [comment] 2017-02-19 09:16
@BluePrintRandom : Some questions:
1) You use a self compiled version ?
2) This version support IK ? (could be checked outside the BGE)
3) Which UPBGE version ?
4) Since when this bug happens ?

**Comment by youle31** [comment] 2017-02-19 11:34
It is an upbge bug (doesn't happen in BF blender (tested in 2.78b and 2.77)). I happened before 0.0.3 (based on 2.76). I'll continue tests later because I've a bad internet connection.

**Comment by youle31** [comment] 2017-02-19 15:38
the bug happened before 0.0.2. 0.0.1 crashes. The bug is not in ge_animrevert

**Comment by panzergame** [comment] 2017-02-25 12:51
I just have to compile with options `WITH_IK_TASK` and `WITH_IK_SOLVER`to solve this issue.

**Comment by panzergame** [comment] 2017-03-10 21:22
Fixed in 222220b9ec94f2fd555c0040370837c77914268e.

**Closed by panzergame** 2017-03-10 21:22 UTC
Labels: bug

**Comment by BluePrintRandom** [comment] 2017-03-24 16:55
I confirm the bug is fixed in 0.1.5 atm*
