### ISSUE TITLE
Display -> World Background Always Off

### ISSUE THREAD

**Issue by adriansnetlis** [UPBGE/blender#425] opened 2017-03-13 17:16 UTC
Whenever I close and reopen a .blend file, the World Background checkbox is always unchecked. This bothers me cuz I always want the background to be visible when I open my .blend file.

**Comment by youle31** [comment] 2017-03-13 17:26
Hi, when you close this when reopen you can't see the background?: http://pasteall.org/blend/index.php?id=45924

**Comment by adriansnetlis** [comment] 2017-03-13 17:30
With this file it seems to leave it on. Weird. Let me pack my file down here.
[Issue.zip](https://github.com/UPBGE/blender/files/839096/Issue.zip)

**Comment by youle31** [comment] 2017-03-13 17:37
When I open your file, world background is not checked. If I enabled woeld background, save the file, close, then reopen, I can see the background

**Comment by adriansnetlis** [comment] 2017-03-13 17:39
I check it every time, save file. When I reopen, it's unchecked.

**Comment by youle31** [comment] 2017-03-13 17:40
weird, I can't reproduce the bug. If you follow exactly the spteps I mention, you still have the problem?

**Comment by adriansnetlis** [comment] 2017-03-13 17:43
Yes. I've repeated it several times and the problem remains. May something be broken in my UPBGE build during compilation?

**Comment by youle31** [comment] 2017-03-13 17:45
I don't know... I can't reproduce the bug on Windows 10 64 upbge 0.1.5 Windows 32

**Comment by adriansnetlis** [comment] 2017-03-13 17:48
Nope, none errors. Running On 64-bit Linux Ubuntu 16.10. The version is 2017-03-06 18:23 with hash be18828.

**Comment by youle31** [comment] 2017-03-13 17:56
Could you try with panzergame build and clear your addons cache. Try to load your .blend with factory settings. Save it with world background enabled. Close, then reopen to see?

**Comment by adriansnetlis** [comment] 2017-03-15 13:43
Just built the latest build of UPBGE and the bug is gone. Could be issue at that specific version or either some build failure that didn't pop as an error during build process.

**Comment by youle31** [comment] 2017-03-15 22:03
ondredenido: Fuck you bastard. If you want some things to be implemented do it yourself asshole

**Closed** 2017-03-15 22:27 UTC
Labels: ?, bug
