### ISSUE TITLE
Animation blendin not working

### ISSUE THREAD

**Issue by joelgomes1994** [UPBGE/blender#605] opened 2017-10-06 23:56 UTC
Hello! I don't know if this was already reported. Look at the test file included.

http://pasteall.org/blend/index.php?id=47990
[animation_test.zip](https://github.com/UPBGE/blender/files/1364134/animation_test.zip)

Blendin is not working when using action actuators.

It works in BFBGE, UPBGE 0.1.9 and early, but not in UPBGE 0.2.0.

**Comment by panzergame** [comment] 2017-10-07 18:24
Hello, I could not reproduce the issue with recent master, could you retest please and provide a video or screenshot ?

**Comment by joelgomes1994** [comment] 2017-10-07 18:26
Could you provide a build, please?

**Comment by joelgomes1994** [comment] 2017-10-07 19:06
Here it is, tested in different versions, only have the issue in UPBGE 0.2.0: https://www.youtube.com/watch?v=tvj8GQC8aGc

**Comment by panzergame** [comment] 2017-10-08 08:01
Fixed in bcfd59ea38441dff170c935facb485e033a3a068.

**Comment by joelgomes1994** [comment] 2017-10-08 08:21
Nice! If needs me to test, could you provide me a build? If not needed, feel free to close the issue. Thanks, and nice work. ;)

**Closed** 2017-10-09 07:43 UTC
