### ISSUE TITLE
Did OpenGL version changed?

### ISSUE THREAD

**Issue by alabd14313** [UPBGE/blender#117] opened 2016-05-22 15:58 UTC
Hi!
UPBGE v0.0.7 view port in my laptop can't show textures (or materials).
intel i915 ==> OpenGL 2.1
![v0 0 7](https://cloud.githubusercontent.com/assets/14325605/15454947/429092e6-205b-11e6-8950-7f38760bca27.png)
What section of veiwport changed?
By LIBGL_ALWAYS_SOFTWARE=1 it is OK. ==>OpenGL 3.3
I didn't tested this version on PC yet.
///////////
UPBGE v0.0.6:
![v0 0 6](https://cloud.githubusercontent.com/assets/14325605/15454964/a5f85f4e-205b-11e6-9665-e1a03bb337bd.png)

**Comment by youle31** [comment] 2016-05-22 16:15
What happens with the last builbot version from BF Blender?
I don't know what change could have caused that in the viewport code... (lodbias? But it only affects textures normally... not materials). Your libs are up to date? Did you run install_deps.sh?

**Comment by alabd14313** [comment] 2016-05-22 16:40
My libs are up to date and all dependencies installed.
BF buildbot haven't this problem.

**Comment by youle31** [comment] 2016-05-22 17:01
Are you familiar with git? If so could you make a bisect to see what commit is responsible of this problem? https://git-scm.com/docs/git-bisect https://git-scm.com/book/en/v2/Git-Tools-Debugging-with-Git (git bisect start, then git bisect bad v0.0.7, then git bisect good v0.0.6, then compile-> if it works, git bisect good, if it doesn't, git bisect bad . And repeat the operation (git bisect good/bad, compile, test) until you find the commit that caused the error.) 

Unfortunately I can't help because I can't reproduce the bug, but if you find the commit, we could have an idea of what's wrong... You could also eventually test linux with static libs release when it will be available to see if the problem is there.

Or maybe panzergame has an idea about this issue.

**Comment by alabd14313** [comment] 2016-05-22 17:32
I found some errors in terminal:

> GPUShader: compile error:
0:2375(6): error: bit-wise operations are forbidden in GLSL 1.20 (GLSL 1.30 or GLSL ES 3.00 required)
0:2375(6): error: type mismatch
0:2376(7): error: bit-wise operations are forbidden in GLSL 1.20 (GLSL 1.30 or GLSL ES 3.00 required)
0:2376(7): error: bit-wise operations are forbidden in GLSL 1.20 (GLSL 1.30 or GLSL ES 3.00 required)
0:2376(7): error: type mismatch
0:2376(6): error: bit-wise operations are forbidden in GLSL 1.20 (GLSL 1.30 or GLSL ES 3.00 required)
0:2377(7): error: bit-wise operations are forbidden in GLSL 1.20 (GLSL 1.30 or GLSL ES 3.00 required)
0:2377(7): error: type mismatch
0:2766(17): error: operator '%' is reserved in GLSL 1.20 (GLSL 1.30 or GLSL ES 3.00 required)
0:2766(27): error: operator '%' is reserved in GLSL 1.20 (GLSL 1.30 or GLSL ES 3.00 required)
0:2766(43): error: operator '%' is reserved in GLSL 1.20 (GLSL 1.30 or GLSL ES 3.00 required)
0:2766(38): error: cannot construct `bool' from a non-numeric data type
0:2766(16): error: operands of `==' must have the same type
0:2784(18): error: operator '%' is reserved in GLSL 1.20 (GLSL 1.30 or GLSL ES 3.00 required)
0:2784(18): error: operands of `!=' must have the same type
0:2785(12): error: operator '%' is reserved in GLSL 1.20 (GLSL 1.30 or GLSL ES 3.00 required)
0:2785(12): error: operands of `!=' must have the same type
0:2793(36): error: bit-wise operations are forbidden in GLSL 1.20 (GLSL 1.30 or GLSL ES 3.00 required)
0:2793(36): error: bit-wise operations are forbidden in GLSL 1.20 (GLSL 1.30 or GLSL ES 3.00 required)
0:2793(36): error: type mismatch
0:2793(53): error: bit-wise operations are forbidden in GLSL 1.20 (GLSL 1.30 or GLSL ES 3.00 required)
0:2793(53): error: type mismatch
0:2793(35): error: operands to arithmetic operators must be numeric
0:2793(21): error: no matching function for call to `integer_noise(error)'; candidates are:
0:2793(21): error:    float integer_noise(int)
0:2793(21): error: operands to arithmetic operators must be numeric
0:2793(14): error: no matching function for call to `clamp(error, float, float)'; candidates are:
0:2793(14): error:    float clamp(float, float, float)
0:2793(14): error:    vec3 clamp(vec3, vec3, vec3)
0:2793(14): error:    float clamp(float, float, float)
0:2793(14): error:    vec2 clamp(vec2, float, float)
0:2793(14): error:    vec3 clamp(vec3, float, float)
0:2793(14): error:    vec4 clamp(vec4, float, float)
0:2793(14): error:    vec2 clamp(vec2, vec2, vec2)
0:2793(14): error:    vec3 clamp(vec3, vec3, vec3)
0:2793(14): error:    vec4 clamp(vec4, vec4, vec4)
0:2793(14): error:    int clamp(int, int, int)
0:2793(14): error:    ivec2 clamp(ivec2, int, int)
0:2793(14): error:    ivec3 clamp(ivec3, int, int)
0:2793(14): error:    ivec4 clamp(ivec4, int, int)
0:2793(14): error:    ivec2 clamp(ivec2, ivec2, ivec2)
0:2793(14): error:    ivec3 clamp(ivec3, ivec3, ivec3)
0:2793(14): error:    ivec4 clamp(ivec4, ivec4, ivec4)
0:2793(9): error: cannot construct `vec2' from a non-numeric data type
0:2793(2): error: `return' with wrong type error, in function `calc_brick_texture' returning vec2

**Comment by youle31** [comment] 2016-05-23 00:06
This error seems to come from this commit: https://developer.blender.org/rBb79214bbc54635ee76c41fd80a1bc67530770d63
from 20 may 2016.

The thing that is weird is that you have not this issue with the last builbot version (unless its date is < 20 may 2016).

So it's not related to upbge but with viewport official BF blender. You can eventually make a bug report if you don't find a solution... Maybe check your drivers.

Or you can try to contact a viewport dev on #blendercoders...

**Comment by alabd14313** [comment] 2016-05-23 06:48
blender-2.77-a2669b0-linux-glibc219 23 may 2016 is OK!
Where is this bug!

**Comment by youle31** [comment] 2016-05-23 07:02
I don't know...

**Comment by adriansnetlis** [comment] 2016-05-23 10:23
Just a note - I see the exact same thing whenever I have node material with Geometry node and no UVs selected. It's not showing up, only the outline object.

**Comment by youle31** [comment] 2016-05-23 13:04
> blender-2.77-a2669b0-linux-glibc219 23 may 2016 is OK!

Did you enable GLSL mode to test in the buildbot version? (multitexture mode is still the default in BF Blender whereas we have GLSL as default (we removed multitexture mode))

Could you share your .blend? in the case I missed something?

If you can connect on #upbgecoders we could try to solve the bug via team viewer if it's upbge related (but the errors you have in the console seems not related to upbge code...)

**Comment by alabd14313** [comment] 2016-05-23 18:27
When I switch to game engine and press Alt + Z, this bug appears.
Eventually I install Linux on a PC tomorrow and test it.
I started bisect debugging, but my laptop is weak for about 7 pass compile. SO I continue it in PC.
Thanks!

**Comment by panzergame** [comment] 2016-06-04 16:28
@alabd14313 : Any news ?

**Comment by alabd14313** [comment] 2016-06-05 13:33
Excuse me, because of delay!
On PC with OpenGL 3.3 is ok and there is not any bug.
I will continue bisect in laptop with OpenGL 2.1 (GLSL 1.2).

**Comment by panzergame** [comment] 2016-06-10 23:26
Any news ?

**Comment by alabd14313** [comment] 2016-06-12 13:26
Please see commit: https://github.com/UPBGE/blender/commit/7ab55d894713fede179df652ba59cc241658dc28
[Support gradient Cycles texture in GLSL viewport](https://developer.blender.org/rB7ab55d894713fede179df652ba59cc241658dc28)

**Comment by youle31** [comment] 2016-06-12 13:50
@alabd14313 : Hi, are you 100% sure this is the bad commit? I bet this is its parent commit :) (the commit just before the one you indicate) https://developer.blender.org/rBb79214bbc54635ee76c41fd80a1bc67530770d63 like I said in the post above.

Anyway, you have to report the issue here: https://developer.blender.org/maniphest/project/2/type/Bug/ top right corner. It is not upbge related and it has to be fixed in the official blender sources. Maybe you will have to suscribe.

I quote myself:

"This error seems to come from this commit: https://developer.blender.org/rBb79214bbc54635ee76c41fd80a1bc67530770d63
from 20 may 2016.

So it seems not related to upbge but with viewport official BF blender. You can eventually make a bug report if you don't find a solution...

Or you can try to contact a viewport dev (or directly Sergey Sharybin) on #blendercoders (IRC freenode)..."

I hope there will be a fix soon, before next upbge version.

**Comment by alabd14313** [comment] 2016-06-12 14:35
Thanks @youle31!
Why blender official buildbot havn't this bug!!!

**Comment by youle31** [comment] 2016-06-12 14:40
and if you build last upbge?

**Comment by youle31** [comment] 2016-06-13 06:43
So I close the bug report because it seems it is not here in the last upbge sources.

@alabd14313 : I explain to you how merges commits from official Blender works:
~each week panzergame import code from official Blender sources into upbge. This means that if there is a bug in the official sources when we import code from official Blender, this bug will be in upbge too.
~each month we change the flag of the upbge (v0.0.6, v0.0.7...).

What happened I think here is that when we set the flag for upbge 0.0.7, we had the bug (https://developer.blender.org/rBb79214bbc54635ee76c41fd80a1bc67530770d63) from official blender sources into upbge. This bug has been solved few days after (https://developer.blender.org/rBbff095184a144a3c9ba4414a8ee71e6b1d43fd78) in blender official sources. So when we imported code from Blender into upbge again, this bug was fixed and we haven't it anymore into upbge.

So when you built upbge, I guess you did: git checkout v0.0.7 (there was the bug) and you built upbge.

If you realize that there is a bug with v0.0.7, you can check if the bug is still there in the last upbge sources. For this, you can do:
git checkout master
git pull --rebase (to update the sources) or git pull
if you have submodules, git submodule foreach git pull --rebase origin master
and then you can build the last sources with:
make update
make full or make lite (for a lite build)

I don't know arch but I follow what is written here: https://wiki.blender.org/index.php/Dev:Doc/Building_Blender/Linux/Arch/CMake

Also, don't forget to always have your dependancies up to date.

If the bug is not here anymore with the last sources, then all is fine and you can use this build and share it on BA forum for arch linux users :)

parenthesis: before doing a bisect, allways ensure the bug is there in the last upbge sources. If it is in the last upbge sources, do:
git checkout master
git pull
compile to test
if bad:
git bisect start
git bisect bad master
git bisect good the hash of the last known good version or the last working version v0.0.6
...
when you find the bad commit copy the hash of the commit and report it in your bug report.
git bisect reset (to stop bisecting)

**Closed by youle31** 2016-06-13 06:43 UTC
Labels: bug
